[package]
name = "heatswap"
version = "0.1.0"
edition = "2021"

[dependencies]
glob = "0.3.2"
gumdrop = "0.8.1"
log = "0.4.27"
regex = "1.11.1"
simplelog = "0.12.2"
thiserror = "2.0.3"

[[bin]]
name = "heatswap"
path = "src/heatswap.rs"

[[bin]]
name = "heatswap-cleanup"
path = "src/cleanup.rs"
