set windows-shell := ["powershell.exe", "-NoProfile", "-Command"]

[private]
default:
    @just --list

deploy:
    cargo build --release
    cp target\release\archive-code.exe \\hssieng\SNDataDev\OYSPlugins\HeatSwap\archive-code.exe
    cp target\release\archive-code.exe \\hssieng\SNDataQas\OYSPlugins\HeatSwap\archive-code.exe
    cp target\release\archive-code.exe \\hssieng\SNDataPrd\OYSPlugins\HeatSwap\archive-code.exe
    cp target\release\archive-code.exe \\hssieng\SNData\SNDataPrdNew\OYSPlugins\HeatSwap\archive-code.exe
