set windows-shell := ["powershell.exe", "-NoProfile", "-Command"]

[private]
default:
    @just --list

test:
    cargo run --bin heatswap -- Kinetic_K5000XMC 123 "test1,w34x,456"
    cat LogData/heatswap.log

deploy:
    cargo build --release
    cp target\release\archive-code.exe \\hssieng\SNDataDev\OYSPlugins\HeatSwap\archive-code.exe
    cp target\release\archive-code.exe \\hssieng\SNDataQas\OYSPlugins\HeatSwap\archive-code.exe
    cp target\release\archive-code.exe \\hssieng\SNDataPrd\OYSPlugins\HeatSwap\archive-code.exe
    cp target\release\archive-code.exe \\hssieng\SNData\SNDataPrdNew\OYSPlugins\HeatSwap\archive-code.exe
